name = "SimpleDataLearner"
uuid = "9b5c4c24-6a1d-4fca-b7c0-ddc0bd6dbc37"
authors = ["bernd <bernd.mehnert@artengis.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
